Repository Goal-Tracker/blooming-backend, pull requests merged in 2024-02, with the labels that each got.

#42 골 조회 기능 추가
  src/docs/asciidoc/goal.adoc
  src/main/java/com/backend/blooming/exception/GlobalExceptionHandler.java
  src/main/java/com/backend/blooming/goal/application/GoalService.java
  src/main/java/com/backend/blooming/goal/application/dto/CreateGoalDto.java
  src/main/java/com/backend/blooming/goal/application/dto/ReadAllGoalDto.java
  src/main/java/com/backend/blooming/goal/application/dto/ReadGoalDetailDto.java
  src/main/java/com/backend/blooming/goal/application/exception/NotFoundGoalTeamException.java
  src/main/java/com/backend/blooming/goal/infrastructure/repository/GoalRepository.java
  src/main/java/com/backend/blooming/goal/presentation/GoalController.java
  src/main/java/com/backend/blooming/goal/presentation/dto/response/ReadAllGoalResponse.java
  src/main/java/com/backend/blooming/goal/presentation/dto/response/ReadGoalResponse.java
  src/main/resources/static/docs/docs.html
  src/main/resources/static/docs/goal.html
  src/main/resources/static/docs/notification.html
  src/test/java/com/backend/blooming/friend/infrastructure/repository/FriendRepositoryTestFixture.java
  src/test/java/com/backend/blooming/goal/application/GoalServiceTest.java
  src/test/java/com/backend/blooming/goal/application/GoalServiceTestFixture.java
  src/test/java/com/backend/blooming/goal/infrastructure/repository/GoalRepositoryTest.java
  src/test/java/com/backend/blooming/goal/infrastructure/repository/GoalRepositoryTestFixture.java
  src/test/java/com/backend/blooming/goal/presentation/GoalControllerTest.java
  src/test/java/com/backend/blooming/goal/presentation/GoalControllerTestFixture.java
Labels: feature

#46 스크립트 실행 명령어 수정
  .github/workflows/dev-cd.yml
Labels: bug

#45 추가 컨벤션에 따른 친구, 사용자 관련 코드 리팩터링
  src/main/java/com/backend/blooming/friend/application/FriendService.java
  src/main/java/com/backend/blooming/user/application/UserService.java
  src/main/java/com/backend/blooming/user/domain/User.java
  src/test/java/com/backend/blooming/user/infrastructure/repository/UserRepositoryTest.java
Labels: refactor

#48 사용자 로그아웃, 탈퇴 기능 구현
  src/main/java/com/backend/blooming/authentication/application/AuthenticationService.java
  src/main/java/com/backend/blooming/authentication/application/BlackListTokenService.java
  src/main/java/com/backend/blooming/authentication/application/dto/LogoutDto.java
  src/main/java/com/backend/blooming/authentication/application/exception/AlreadyRegisterBlackListTokenException.java
  src/main/java/com/backend/blooming/authentication/configuration/AuthenticationWebMvcConfiguration.java
  src/main/java/com/backend/blooming/authentication/domain/BlackListToken.java
  src/main/java/com/backend/blooming/authentication/infrastructure/blacklist/BlackListTokenRepository.java
  src/main/java/com/backend/blooming/authentication/presentation/AuthenticationController.java
  src/main/java/com/backend/blooming/authentication/presentation/dto/LogoutRequest.java
  src/main/java/com/backend/blooming/authentication/presentation/dto/WithdrawRequest.java
  src/main/java/com/backend/blooming/devicetoken/application/service/DeviceTokenService.java
  src/main/java/com/backend/blooming/exception/ExceptionMessage.java
  src/main/java/com/backend/blooming/exception/GlobalExceptionHandler.java
  src/test/java/com/backend/blooming/authentication/application/AuthenticationServiceTest.java
  src/test/java/com/backend/blooming/authentication/application/AuthenticationServiceTestFixture.java
  src/test/java/com/backend/blooming/authentication/application/BlackListTokenServiceTest.java
  src/test/java/com/backend/blooming/authentication/application/BlackListTokenServiceTestFixture.java
  src/test/java/com/backend/blooming/authentication/infrastructure/blacklist/BlackListTokenRepositoryTest.java
  src/test/java/com/backend/blooming/authentication/infrastructure/blacklist/BlackListTokenRepositoryTestFixture.java
  src/test/java/com/backend/blooming/authentication/presentation/AuthenticationControllerTest.java
  src/test/java/com/backend/blooming/authentication/presentation/AuthenticationControllerTestFixture.java
  src/test/java/com/backend/blooming/devicetoken/application/service/DeviceTokenServiceTest.java
Labels: feature

#51 dev 서버용 관리자 테스트 페이지 추가
  build.gradle
  src/main/java/com/backend/blooming/admin/application/AdminPageService.java
  src/main/java/com/backend/blooming/admin/controller/AdminPageController.java
  src/main/java/com/backend/blooming/admin/controller/dto/CreateGoalRequest.java
  src/main/java/com/backend/blooming/admin/controller/dto/CreateUserRequest.java
  src/main/java/com/backend/blooming/admin/controller/dto/FriendStatus.java
  src/main/java/com/backend/blooming/admin/controller/dto/RequestFriendRequest.java
  src/main/java/com/backend/blooming/admin/controller/dto/UpdateFriendRequest.java
  src/main/java/com/backend/blooming/admin/controller/exception/InvalidFriendStatusException.java
  src/main/java/com/backend/blooming/authentication/configuration/AuthenticationWebMvcConfiguration.java
  src/main/java/com/backend/blooming/exception/ExceptionMessage.java
  src/main/java/com/backend/blooming/exception/GlobalExceptionHandler.java
  src/main/java/com/backend/blooming/friend/application/FriendService.java
  src/main/java/com/backend/blooming/friend/application/exception/AlreadyRequestedFriendException.java
  src/main/java/com/backend/blooming/friend/application/exception/FriendRequestNotAllowedException.java
  src/main/java/com/backend/blooming/friend/infrastructure/repository/FriendRepository.java
  src/main/resources/templates/admin/test.html
  src/test/java/com/backend/blooming/admin/application/AdminPageServiceTest.java
  src/test/java/com/backend/blooming/admin/application/AdminPageServiceTestFixture.java
  src/test/java/com/backend/blooming/admin/controller/AdminPageControllerTest.java
  src/test/java/com/backend/blooming/admin/controller/AdminPageControllerTestFixture.java
  src/test/java/com/backend/blooming/friend/application/FriendServiceTest.java
  src/test/java/com/backend/blooming/friend/infrastructure/repository/FriendRepositoryTest.java
  src/test/java/com/backend/blooming/friend/infrastructure/repository/FriendRepositoryTestFixture.java
  src/test/java/com/backend/blooming/friend/presentation/FriendControllerTest.java
  src/test/java/com/backend/blooming/user/presentation/UserControllerTest.java
Labels: feature

#54 dev 서버 배포 시 view를 찾지 못하는 문제 해결
  src/main/java/com/backend/blooming/admin/controller/AdminPageController.java
  src/test/java/com/backend/blooming/admin/controller/AdminPageControllerTest.java
Labels: feature

#55 authentication의 presentation 패키지의 클래스 위치 수정
  src/main/java/com/backend/blooming/authentication/application/dto/LogoutDto.java
  src/main/java/com/backend/blooming/authentication/presentation/AuthenticationController.java
  src/main/java/com/backend/blooming/authentication/presentation/dto/WithdrawRequest.java
  src/main/java/com/backend/blooming/authentication/presentation/dto/request/LogoutRequest.java
  src/main/java/com/backend/blooming/authentication/presentation/dto/request/SocialLoginRequest.java
  src/main/java/com/backend/blooming/authentication/presentation/dto/request/WithdrawRequest.java
  src/main/java/com/backend/blooming/notification/presentation/NotificationController.java
  src/main/java/com/backend/blooming/notification/presentation/dto/response/ReadNotificationsResponse.java
  src/test/java/com/backend/blooming/authentication/presentation/AuthenticationControllerTestFixture.java
Labels: refactor

#60 인증 인터셉터에서 로그인와 토큰 재발급 제외
  src/main/java/com/backend/blooming/authentication/configuration/AuthenticationWebMvcConfiguration.java
Labels: bug

#43 골 수정 및 삭제 기능 구현
  src/docs/asciidoc/goal.adoc
  src/main/java/com/backend/blooming/exception/ExceptionMessage.java
  src/main/java/com/backend/blooming/exception/GlobalExceptionHandler.java
  src/main/java/com/backend/blooming/goal/application/GoalService.java
  src/main/java/com/backend/blooming/goal/application/dto/ReadAllGoalDto.java
  src/main/java/com/backend/blooming/goal/application/dto/ReadGoalDetailDto.java
  src/main/java/com/backend/blooming/goal/application/dto/UpdateGoalDto.java
  src/main/java/com/backend/blooming/goal/application/exception/DeleteGoalForbiddenException.java
  src/main/java/com/backend/blooming/goal/application/exception/InvalidGoalException.java
  src/main/java/com/backend/blooming/goal/application/exception/UpdateGoalForbiddenException.java
  src/main/java/com/backend/blooming/goal/domain/Goal.java
  src/main/java/com/backend/blooming/goal/domain/GoalTeam.java
  src/main/java/com/backend/blooming/goal/domain/GoalTerm.java
  src/main/java/com/backend/blooming/goal/domain/Teams.java
  src/main/java/com/backend/blooming/goal/infrastructure/repository/GoalRepository.java
  src/main/java/com/backend/blooming/goal/presentation/GoalController.java
  src/main/java/com/backend/blooming/goal/presentation/dto/request/UpdateGoalRequest.java
  src/main/java/com/backend/blooming/goal/presentation/dto/response/ReadGoalResponse.java
  src/main/resources/static/docs/authentication.html
  src/main/resources/static/docs/docs.html
  src/main/resources/static/docs/goal.html
  src/test/java/com/backend/blooming/goal/application/GoalServiceTest.java
  src/test/java/com/backend/blooming/goal/application/GoalServiceTestFixture.java
  src/test/java/com/backend/blooming/goal/domain/GoalTermTest.java
  src/test/java/com/backend/blooming/goal/domain/GoalTermTestFixture.java
  src/test/java/com/backend/blooming/goal/domain/GoalTest.java
  src/test/java/com/backend/blooming/goal/domain/GoalTestFixture.java
  src/test/java/com/backend/blooming/goal/domain/TeamsTest.java
  src/test/java/com/backend/blooming/goal/domain/TeamsTestFixture.java
  src/test/java/com/backend/blooming/goal/infrastructure/repository/GoalRepositoryTest.java
  src/test/java/com/backend/blooming/goal/presentation/GoalControllerTest.java
  src/test/java/com/backend/blooming/goal/presentation/GoalControllerTestFixture.java
  src/test/java/com/backend/blooming/user/infrastructure/repository/UserRepositoryTest.java
Labels: feature

#66 사용자 정보 수정 시 이름 중복 문제에 대한 예외 처리 추가
  src/main/java/com/backend/blooming/exception/ExceptionMessage.java
  src/main/java/com/backend/blooming/exception/GlobalExceptionHandler.java
  src/main/java/com/backend/blooming/user/application/UserService.java
  src/main/java/com/backend/blooming/user/application/exception/DuplicateUserNameException.java
  src/main/java/com/backend/blooming/user/domain/Name.java
  src/main/java/com/backend/blooming/user/domain/User.java
  src/main/java/com/backend/blooming/user/infrastructure/repository/UserRepository.java
  src/test/java/com/backend/blooming/user/application/UserServiceTest.java
  src/test/java/com/backend/blooming/user/application/UserServiceTestFixture.java
  src/test/java/com/backend/blooming/user/domain/NameTest.java
  src/test/java/com/backend/blooming/user/domain/UserTest.java
  src/test/java/com/backend/blooming/user/infrastructure/repository/UserRepositoryTest.java
  src/test/java/com/backend/blooming/user/infrastructure/repository/UserRepositoryTestFixture.java
  src/test/java/com/backend/blooming/user/presentation/UserControllerTest.java
Labels: refactor
